/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.MovestoqueDAO;
import dao.ProdutoDAO;
import dao.RelatoriosDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Back
 */
public class IfrConsultaEstoque extends javax.swing.JInternalFrame {

    /** Creates new form IfrConsultaEstoque */
    public IfrConsultaEstoque() {
        initComponents();
        ProdutoDAO prodDAO = new ProdutoDAO();
        Formatacao.formatarData(tfdFdataIniciall);
        Formatacao.formatarHora(tfdFHoraInicial);
        Formatacao.formatarHora(tfdFHoraFinal);
        Formatacao.formatarData(tfdFdataFinal);
        prodDAO.popularComboGrupo(jComboBoxGrupo);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdFdataIniciall = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMov = new javax.swing.JTable();
        tfdFdataFinal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdFHoraInicial = new javax.swing.JFormattedTextField();
        tfdFHoraFinal = new javax.swing.JFormattedTextField();
        jComboBoxGrupo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxOper = new javax.swing.JComboBox<>();
        BtnCarregarInfo = new javax.swing.JButton();

        tfdFdataIniciall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataIniciallActionPerformed(evt);
            }
        });

        jTableMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Período", "Produto", "Grupo", "Operação", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTableMov);

        tfdFdataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataFinalActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jLabel3.setText("Hora Inicial");

        jLabel4.setText("Hora Final");

        tfdFHoraInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraInicialActionPerformed(evt);
            }
        });

        tfdFHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraFinalActionPerformed(evt);
            }
        });

        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));

        jLabel5.setText("Grupo");

        jLabel6.setText("Operação");

        jComboBoxOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Entrada", "Saída" }));

        BtnCarregarInfo.setText("Gerar");
        BtnCarregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdFdataIniciall, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(BtnCarregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxGrupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdFdataIniciall, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(BtnCarregarInfo)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdFdataIniciallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataIniciallActionPerformed

    }//GEN-LAST:event_tfdFdataIniciallActionPerformed

    private void tfdFdataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFdataFinalActionPerformed

    private void tfdFHoraInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraInicialActionPerformed

    private void tfdFHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraFinalActionPerformed

    private void BtnCarregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarInfoActionPerformed
           Validacao valida = new Validacao();
            String dataini = tfdFdataIniciall.getText();
            String datafi = tfdFdataFinal.getText();
            String horaini = tfdFHoraInicial.getText();
            String horafi = tfdFHoraFinal.getText();
            int codgrupo = jComboBoxGrupo.getSelectedIndex();
            int codoper = jComboBoxOper.getSelectedIndex();
        if ((valida.validarDataFormatada(tfdFdataIniciall.getText()) == false) || (valida.validarDataFormatada(tfdFdataFinal.getText()) == false)) {
             JOptionPane.showMessageDialog(null, "A data preenchida é inválida");
         } else { 
         if ((valida.validaHora(tfdFHoraInicial.getText()) == false) || (valida.validaHora(tfdFHoraFinal.getText()) == false))  {
             JOptionPane.showMessageDialog(null, "A hora preenchida é inválida");  
         } else {
             if (jComboBoxGrupo.getSelectedIndex() == 0) {
               JOptionPane.showMessageDialog(null, "Por favor selecione um grupo"); 
         } else {
                if (jComboBoxOper.getSelectedIndex() == 0) {
               JOptionPane.showMessageDialog(null, "Por favor selecione uma operação");  
             } else {
                    new RelatoriosDAO().popularTabela(jTableMov,dataini,datafi,horaini,horafi,codgrupo,codoper);
                }
             }
         }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCarregarInfoActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarregarInfo;
    private javax.swing.JComboBox<String> jComboBoxGrupo;
    private javax.swing.JComboBox<String> jComboBoxOper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMov;
    private javax.swing.JFormattedTextField tfdFHoraFinal;
    private javax.swing.JFormattedTextField tfdFHoraInicial;
    private javax.swing.JFormattedTextField tfdFdataFinal;
    private javax.swing.JFormattedTextField tfdFdataIniciall;
    // End of variables declaration//GEN-END:variables

}
