/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import apoio.ConexaoBD;
import apoio.Formatacao;
import apoio.Validacao;
import dao.MovestoqueDAO;
import dao.ProdutoDAO;
import dao.RelatoriosDAO;
import entidade.Produto;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Back
 */
public class IfrRelatorioMovimentacao extends javax.swing.JInternalFrame {

    /** Creates new form IfrConsultaEstoque */
    public IfrRelatorioMovimentacao() {
        initComponents();
        ProdutoDAO prodDAO = new ProdutoDAO();
        Formatacao.formatarHora(tfdFHoraInicial);
        Formatacao.formatarHora(tfdFHoraFinal);
        Formatacao.formatarData(tfdFdataFinal);
        Formatacao.formatarData(tfdFdataInicial);
        tfdSelecProd.setEditable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdSelecProd = new javax.swing.JFormattedTextField();
        tfdFHoraInicial = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxOper = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfdFdataFinal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdFHoraFinal = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdPesquisarProd = new javax.swing.JFormattedTextField();
        BtnCarregarInfo = new javax.swing.JButton();
        btnPesquisarProd3 = new javax.swing.JButton();
        btnCarregarInfo1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TProduto = new javax.swing.JTable();
        btnPesquisarSecoes = new javax.swing.JButton();
        tfdFdataInicial = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("Data Inicial");

        tfdSelecProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdSelecProdActionPerformed(evt);
            }
        });

        tfdFHoraInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora Inicial");

        jLabel6.setText("Operação");

        jComboBoxOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Entrada", "Saída" }));

        jLabel2.setText("Data Final");

        tfdFdataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataFinalActionPerformed(evt);
            }
        });

        jLabel4.setText("Hora Final");

        tfdFHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tfdFHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFHoraFinalActionPerformed(evt);
            }
        });

        jLabel7.setText("Pesquisar Produto");

        tfdPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPesquisarProdActionPerformed(evt);
            }
        });

        BtnCarregarInfo.setText("Gerar Relatório");
        BtnCarregarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarregarInfoActionPerformed(evt);
            }
        });

        btnPesquisarProd3.setText("Fechar");
        btnPesquisarProd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProd3ActionPerformed(evt);
            }
        });

        btnCarregarInfo1.setText("Selecionar Produto");
        btnCarregarInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarInfo1ActionPerformed(evt);
            }
        });

        TProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Descrição", "Cor", "Marca", "Tamanho", "Quantidade", "Seção", "Grupo", "Prateleira"
            }
        ));
        jScrollPane1.setViewportView(TProduto);

        btnPesquisarSecoes.setText("Pesquisar");
        btnPesquisarSecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSecoesActionPerformed(evt);
            }
        });

        tfdFdataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFdataInicialActionPerformed(evt);
            }
        });

        jLabel5.setText("Produto Selecionado (Id)");

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Consulta de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarProd3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCarregarInfo1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfdPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisarSecoes))))))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdFdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(BtnCarregarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfdSelecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdFHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarregarInfo)
                    .addComponent(tfdFdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdFdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfdFHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdSelecProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarSecoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarregarInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimparCampos)
                    .addComponent(btnPesquisarProd3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdSelecProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdSelecProdActionPerformed

    }//GEN-LAST:event_tfdSelecProdActionPerformed

    private void tfdFdataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFdataFinalActionPerformed

    private void tfdFHoraInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraInicialActionPerformed

    private void tfdFHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFHoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFHoraFinalActionPerformed

    private void BtnCarregarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarregarInfoActionPerformed
           Validacao valida = new Validacao();
            RelatoriosDAO rdao = new RelatoriosDAO();

            String dataini = tfdFdataInicial.getText();
            String datafi = tfdFdataFinal.getText();
            String horaini = tfdFHoraInicial.getText();
            String horafi = tfdFHoraFinal.getText();
            String sql = ""; //monta o where
            int aux = 0; // auxiliar para testar se tem produto selecionado, se não tiver 0 vai representar todos
            String z = tfdSelecProd.getText(); // ve se tem algum produto selecionado
            int codoper = jComboBoxOper.getSelectedIndex();
            String operacao = "";
           
                    
        if ((valida.validarDataFormatada(tfdFdataInicial.getText()) == false) || (valida.validarDataFormatada(tfdFdataFinal.getText()) == false) || dataini.isEmpty() || datafi.isEmpty()) {
             JOptionPane.showMessageDialog(null, "A data preenchida é inválida ou o campo está vazio");
         } else { 
         if ((valida.validaHora(tfdFHoraInicial.getText()) == false) || (valida.validaHora(tfdFHoraFinal.getText()) == false) || (horaini.isEmpty()) || (horafi.isEmpty()))  {
             JOptionPane.showMessageDialog(null, "A hora preenchida é inválida ou o campo está vazio");  
         } else {
                if (jComboBoxOper.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Por favor selecione uma operação");  
                } else {
                   if (z.isEmpty() == false) {
                       aux = Integer.parseInt(z);
                   }
                }
                }
        }
            if (codoper == 1) {
                operacao = "E";
            } else {
                operacao = "S";
            }
            if (aux == 0) {
                sql = "m.periodo BETWEEN '" + dataini + " " + horaini + "' AND '" + datafi + " " + horafi + "' AND m.operacao = '" + operacao + "'";
            } else {
                sql = "m.periodo BETWEEN '" + dataini + " " + horaini + "' AND '" + datafi + " " + horafi + "' AND m.operacao = '" + operacao + "' AND p.id = " + aux;
            }
                 Connection connection = null;
        try {
            // Obtém a conexão com o banco de dados
            connection = ConexaoBD.getInstance().getConnection();

            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport relatorio = JasperCompileManager.compileReport(getClass().getResourceAsStream("/relatorios/MovEstoque.jrxml"));
            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();
            param.put("sql", sql);

            // Gera o relatório efetivamente
            JasperPrint print;
            print = JasperFillManager.fillReport(relatorio, param, connection);

            // Exibir o relatório
            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCarregarInfoActionPerformed

    private void btnPesquisarProd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProd3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPesquisarProd3ActionPerformed

    private void tfdPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPesquisarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdPesquisarProdActionPerformed

    private void btnCarregarInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarInfo1ActionPerformed
        String idString = String.valueOf(TProduto.getValueAt(TProduto.getSelectedRow(), 0));

        int idS = Integer.parseInt(idString);        // criar instancia ProdutoDAO
        ProdutoDAO prodDAO = new ProdutoDAO();

        // criar instancia Produto
        Produto produto = prodDAO.consultarIdAux(idS);

        if (produto != null) {
            
            tfdSelecProd.setText(""+produto.getId());
           // tfdConsultarProduto.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um produto");
        }
    }//GEN-LAST:event_btnCarregarInfo1ActionPerformed

    private void btnPesquisarSecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSecoesActionPerformed
        new ProdutoDAO().popularTabela(TProduto,tfdPesquisarProd.getText());

    }//GEN-LAST:event_btnPesquisarSecoesActionPerformed

    private void tfdFdataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFdataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFdataInicialActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        tfdFHoraFinal.setText("");
        tfdFHoraInicial.setText("");
        tfdFdataFinal.setText("");
        tfdFdataInicial.setText("");
        tfdPesquisarProd.setText("");
        tfdSelecProd.setText("");
    }//GEN-LAST:event_btnLimparCamposActionPerformed

 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarregarInfo;
    private javax.swing.JTable TProduto;
    private javax.swing.JButton btnCarregarInfo1;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPesquisarProd3;
    private javax.swing.JButton btnPesquisarSecoes;
    private javax.swing.JComboBox<String> jComboBoxOper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField tfdFHoraFinal;
    private javax.swing.JFormattedTextField tfdFHoraInicial;
    private javax.swing.JFormattedTextField tfdFdataFinal;
    private javax.swing.JFormattedTextField tfdFdataInicial;
    private javax.swing.JFormattedTextField tfdPesquisarProd;
    private javax.swing.JFormattedTextField tfdSelecProd;
    // End of variables declaration//GEN-END:variables

}
